Merge conda install back into one command via conda-forge + fallback

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -131,13 +131,14 @@ install:
     - export PATH="$HOME/miniconda/bin:$PATH"
     - hash -r
     - conda update -yq conda
-    - conda install -y gtest cmake #xtensor -c conda-forge
     - |
-      # install xtensor (and fftw on osx); if conda fails, use xtensor from source
+      # install deps with conda: cmake, gtest, xtensor (and fftw on osx); if conda-forge fails, use xtensor from source
       if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
-        conda install -y xtensor fftw -c conda-forge
+        conda install -y gtest cmake xtensor fftw -c conda-forge
       elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
-        if ! conda install -y xtensor -c conda-forge; then
+        if ! conda install -y gtest cmake xtensor -c conda-forge; then
+          echo "conda-forge install failed! Installing gtest and cmake from default conda channel."
+          conda install -y gtest cmake
           echo "Installing xtensor from source"
           cd $TRAVIS_HOME
           git clone https://github.com/QuantStack/xtensor.git
